### DISCUSSION TITLE
containerd use harbor, configure CA certificate

### DISCUSSION THREAD

**Discussion by jan-bar** [labring/sealos#1126] [General]
1. generate certificate: <https://goharbor.io/docs/2.5.0/install-config/configure-https/>
2. copy the certificate: `scp ca.crt root@nodeIp:/usr/local/share/ca-certificates/harbor.crt` (**sealos3.0**), The directory does not exist and needs to be 
created manually. `scp ca.crt root@nodeIp:/etc/ssl/certs/harbor.crt` (**sealos4.0**)
3. restart containerd : `systemctl restart containerd.service `
4. k8a master create secrets: `kubectl create secret docker-registry janbar-harbor  --docker-server=x.x.x.x  --docker-username=admin  --docker-password=Harbor12345`
5. can be used directly
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "my-nginx"
  namespace: default
  labels:
    app: "my-nginx"
spec:
  imagePullSecrets:
    - name: janbar-harbor
  containers:
    - image: x.x.x.x/nginx:alpine
      name: my-container-01
      imagePullPolicy: Always
```

Solution source: <https://github.com/haminhcong/k8s-til/issues/17>, **Solution 3**
