### DISCUSSION TITLE
example: how to run a pod on sealos cloud

### DISCUSSION THREAD

**Discussion by wuxming** [labring/sealos#1957] [General] [answered]
```
apiVersion: v1
kind: Pod
metadata:
  name: my-first-demo
  labels:
    app: my-first-demo
spec:
  containers:
    - name: my-first-demo
      image: hellodm/my-first-demo:v1.0
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 0.1
          memory: 32Mi
        limits:
          cpu: 0.5
          memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-first-demo-svc
  labels:
    app: my-first-demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80

  selector:
    app: my-first-demo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: hello-world
  labels:
    k8s-app: hello-world
spec:
  rules:
    - host: hello.cloud.sealos.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: my-first-demo-svc 
                port:
                  number: 8080
  tls:
    - hosts:
        - hello.cloud.sealos.io
      secretName: wildcard-cloud-sealos-io-cert
```

<img width="448" alt="image" src="https://user-images.githubusercontent.com/8912557/197682548-86a1cf36-c090-4fd2-a769-684ef17de892.png">
