### DISCUSSION TITLE
parse config.yaml with nodename

### DISCUSSION THREAD

**Discussion by weironz** [labring/sealos#3521] [General] [answered]
config.yaml
```
hosts:
- {name: node1, address: 172.16.0.2, port: 22, user: ubuntu, password: "Ubuntu@123"}
- {name: node2, address: 172.16.0.3, port: 22, user: ubuntu, password: "Ubuntu@123"}
- {name: node3, address: 172.16.0.4, port: 22, user: ubuntu, password: "Ubuntu@123"}
- {name: node4, address: 172.16.0.5, port: 22, user: ubuntu, password: "Ubuntu@123"}
- {name: node5, address: 172.16.0.6, port: 22, user: ubuntu, password: "Ubuntu@123"}
- {name: node6, address: 172.16.0.7, port: 22, user: ubuntu, password: "Ubuntu@123"}
roleGroups:
  etcd:
  - node1
  - node2
  - node3
  ceph:
  - node1
  - node2
  - node3
  master:
  - node1
  - node2
  - node3
  worker:
  - node1
  - node2
  - node3
```
Clusterfile.yaml, this not work, 
I would like to know if it is possible to achieve this complex rendering through the go template. Can someone help me ?

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    {{range .Values.hosts}}
    {{if eq .name .roleGroups.master}}
    - {{.address}}
    {{end}}
    {{end}}
    roles:
    - master
    - amd64
  image:
  - registry.cn-hongkong.aliyuncs.com/labring/kubernetes:v1.25.6
```
run command
```
sealos apply -f Clusterfile.yaml --values config.yaml  --debug
```
and what i hope the final Clusterfile will be this:
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    - 172.16.0.2
    - 172.16.0.3
    - 172.16.0.4
    roles:
    - master
    - amd64
  image:
  - registry.cn-hongkong.aliyuncs.com/labring/kubernetes:v1.25.6
```

**Comment by fengxsong** [comment]
{{if has .name .roleGroups.master}}

**Reply by fengxsong** [reply, marked as answer]
using `$.Values.roleGroups.master` in `range` iter

**Reply by weironz** [reply]
thanks!
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    {{ $default_host := .Values.roleGroups.master }}
    {{- range .Values.hosts }}
    {{ if has .name $default_host }}
    - {{ .address | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
    roles:
    - master
    - amd64
  image:
  - registry.cn-hongkong.aliyuncs.com/labring/kubernetes:v1.25.6
  ssh:
    passwd: 123456
    pk: ~/.ssh/id_rsa
    port: 22
    user: root
```

**Comment by weironz** [comment]
yes ,this `$.Values.roleGroups.master` is better
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    {{- range .Values.hosts }}
    {{ if has .name $.Values.roleGroups.master }}
    - {{ .address | toYaml | nindent 8 }}
    {{- end }}
    {{- end }}
    roles:
    - master
    - amd64
  image:
  - registry.cn-hongkong.aliyuncs.com/labring/kubernetes:v1.25.6
  ssh:
    passwd: 123456
    pk: ~/.ssh/id_rsa
    port: 22
    user: root
```
