### ISSUE TITLE
open podpreset by default.

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1001]
https://kubernetes.io/es/docs/concepts/workloads/pods/podpreset/

So can use it to set TZ to all pods.
```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: setting-timezone
spec:
  env:
    - name: TZ
      value: Asia/Shanghai
```
