### ISSUE TITLE
【sealos4.0版本】初始化时，--podcidr参数去掉后，我应该如何修改podcidr

### ISSUE THREAD

**Issue by xwc1125** [labring/sealos#1119]
**那个命令或者组件**
sealos init 

**描述你的问题**
由于服务器的一些限制，无法直接使用100.64的网段，因此需要将podcidr网段进行修改。但是目前不清楚该怎么去修改。

**你看到的一些参考资料**
[使用教程](https://www.sealyun.com/instructions/2)
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/4408289/172978623-b01dc875-cdad-42cd-b858-cfee2e0fd7e5.png">

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/blob/main/applications/calico/Clusterfile

**Comment by gitccl** [comment]
1. run `sealos reset` to reset your cluster if you have started the cluster.
2. run `sealos gen` to generate a Clusterfile. e.g. `sealos gen labring/kubernetes:v1.24.0 labring/calico:v3.22.1 --masters 192.168.0.2,192.168.0.3,192.168.0.4 --nodes 192.168.0.5,192.168.0.6,192.168.0.7 --passwd xxx > Clusterfile`.
3. Append the [calico Clusterfile](https://github.com/labring/sealos/blob/main/applications/calico/Clusterfile) to the Clusterfile that generated in step2, and change the `networking.podSubnet` and `spec.data.spec.calicoNetwork.ipPools.cidr` fields. The final Clusterfile will be like this:
    <details>
    <summary>Clusterfile</summary>
    
    ```yaml
    apiVersion: apps.sealos.io/v1beta1
    kind: Cluster
    metadata:
      creationTimestamp: null
      name: default
    spec:
      hosts:
      - ips:
        - 192.168.0.2:22
        - 192.168.0.3:22
        - 192.168.0.4:22
        roles:
        - master
        - amd64
      - ips:
        - 192.168.0.5:22
        - 192.168.0.6:22
        - 192.168.0.7:22
        roles:
        - node
        - amd64
      image:
      - labring/kubernetes:v1.24.0
      - labring/calico:v3.22.1
      ssh:
        passwd: xxx
        pk: /root/.ssh/id_rsa
        port: 22
        user: root
    status: {}
    ---
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    networking:
      podSubnet: 10.160.0.0/12
    ---
    apiVersion: apps.sealos.io/v1beta1
    kind: Config
    metadata:
      name: calico
    spec:
      path: manifests/calico.yaml
      data: |
        apiVersion: operator.tigera.io/v1
        kind: Installation
        metadata:
          name: default
        spec:
          # Configures Calico networking.
          calicoNetwork:
            # Note: The ipPools section cannot be modified post-install.
            ipPools:
            - blockSize: 26
              # Note: Must be the same as podCIDR
              cidr: 10.160.0.0/12
              encapsulation: IPIP
              natOutgoing: Enabled
              nodeSelector: all()
            nodeAddressAutodetectionV4:
              interface: "eth.*|en.*"
    ```
    </details>
4. run `sealos apply -f Clusterfile` to start the cluster.
