### ISSUE TITLE
RPM/DEB for Linux Distributions

### ISSUE THREAD

**Issue by Vonng** [labring/sealos#1133]
Binary is straightforward. But rpm & deb are standard.

Making distribution (rpm|deb) is tedious. Luckily we can build rpm with `nfpm` for standalone binary with one simple config file.

As simple as :

first create an config file, [example](https://github.com/Vonng/pg_exporter/blob/master/nfpm.yaml)

```yaml
# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "sealos"
arch: "amd64"
platform: "linux"
version: "v4.0.0"
version_schema: semver
maintainer: fanux..............
description: blahblahblah
vendor: "labring"
homepage: "https://github.com/labring/sealos"
license: "Apache-2.0 License"

contents:
- src: sealos
  dst: /usr/bin/sealos

```

Then build with nfpm.

```bash
nfpm package --packager rpm
nfpm package --packager deb
```
