### ISSUE TITLE
Feature: sealos applications actions

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1259]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/8912557/177467971-c146debb-04c4-41f1-82a7-7b5d8bc3a1c7.png">

We can define some actions for applications delete upgrade scale...

```
apiVersion: apps.sealos.io/v1beta1
kind: Actions
metadata:
  name: delete
spec:
  shell: kubectl delete -f mysql-cr.yaml 
  # shell: kubectl delete mysql $(instance name)
...
```

Then copy the actions yaml to applications image:
```
FROM mysql:8.0
COPY actions.yaml actions 
```

Then sealos desktop will got the applications actions.
