### ISSUE TITLE
Feature: web terminal controller

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1335]
https://github.com/labring/fist/blob/master/terminal/README.md

https://book.kubebuilder.io/quick-start.html

```
apiVersion: terminal.sealos.io/v1
kind: Terminal
metadata:
  name: aws-infra-demo
spec:
  user: xxx
  token: xxx
  keepalived: 5min
```

Then `kubectl apply -f terminal.yaml` will create a web terminal.
