### ISSUE TITLE
sealos 生成Clusterfile env 指定containerd 路径参数丢失

### ISSUE THREAD

**Issue by he-aook** [labring/sealos#1388]
**Which command or component**

eg. sealos init, sealos install ...

**The Description of the bug**

Describe the bug.

**How to reproduce（pictures can be attached if necessary）**
1. 阿里云服务器默认部署过程中podCidr 与DNS 网段冲突, 修改podcidr之后,再次到处Clusterfile也是看不到podCidr的细节
2. 第一步sealos run 指定 --env criData=/data/containerd 路径, 之后修改Clusterfile.podcidr , 再重新部署,发现containerd的路径还是默认的
3. 以上2步分开验证之后导出Clusterfile 文件内容缺少
...

**Test Result**
```
sealos run labring/kubernetes:v1.24.0 labring/calico:v3.22.1     --masters  10.0.0.80     --nodes 10.0.0.81,10.0.0.86     --passwd 't4C8CGabcddddPpv' --env criData=/data/containerd
```
Clusterfile `内容[root@master ~]# cat Clusterfile
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 10.0.0.80:22
    roles:
    - master
    - amd64
  - ips:
    - 10.0.0.81:22
    - 10.0.0.86:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    passwd: t4C8CGZ3FRvkdddfadf
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status: {}
```

5.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/48249754/180599448-5c6f7bae-489f-4017-aa36-4a13b08928e7.png">

**What you expected to happen**

Expected to xxx

**Operating environment**

- containerd version:   eg.  containerd://1.6.2
- Kubernetes version: eg.labring/kubernetes:v1.24.0
- Sealos version: gitVersion":"4.0.0"
- Operating system: eg. centos7.6
- Runtime environment:  eg. physical machine (32G memory, 8 core cpu, 300G storage), virtual machine (virbox, 32G memory, 
-  8 core cpu, 500G storage), cloud(aws, 32G memory, 8 core cpu, 500G storage)
- Cluster size: eg 1 master, 2 node
- Additional information: istio, dashboard ...
