### ISSUE TITLE
Feature: sealos run --hostname-prefix=node-xxx

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1449]
**Which command or component**
```
sealos run --hostname-prefix=node-xxx
```
**Detailed description of the feature**
Now the only thing must manual do is configure each node hostname, so is it possible configure hostname auto?

**If you have solution，please describe it**

```
sealos run --hostname-prefix=node-xxx
sealos run --hostname-prefix=kube-node00-*
```

and sealos will auto set each node hostname with node-1、node-2  or kube-node001、kube-node002

**Comment by fanux** [comment]
this is a reasonable requirement，However, we can solve it through the plug-in mechanism without adding parameters to the command line.

Like:
```
apiVersion: plugin.sealos.io/v1
kind: Plugin
metadata:
  name: hostname-plugin
spec:
  type: HOSTNAME
  rules: kube-node00-*
```

Then copy it into the image, or add it into Clusterfile.
