### ISSUE TITLE
Feature: Build image have digest

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1451]
**Which command or component**

```
sealos build -f Dockerfile -t registry.cn-shenzhen.aliyuncs.com/cnmirror/cilium:v1.12.0 .
```

i want build cilium app, but there have some image have digest, and run sealos build failed
```
helm repo add cilium https://helm.cilium.io/

root@ubuntu:~# helm show values cilium/cilium |grep image: -A3
image:
  override: ~
  repository: "quay.io/cilium/cilium"
  tag: "v1.12.0"
--
  image:
    override: ~
    repository: "quay.io/cilium/certgen"
    tag: "v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd"
--
    image:
      override: ~
      repository: "quay.io/cilium/hubble-relay"
      tag: "v1.12.0"
--
      image:
        override: ~
        repository: "quay.io/cilium/hubble-ui-backend"
        tag: "v0.9.0@sha256:000df6b76719f607a9edefb9af94dfd1811a6f1b6a8a9c537cba90bf12df474b"
--
      image:
        override: ~
        repository: "quay.io/cilium/hubble-ui"
        tag: "v0.9.0@sha256:0ef04e9a29212925da6bdfd0ba5b581765e41a01f1cc30563cef9b30b457fea0"
--
  image:
    override: ~
    repository: "quay.io/cilium/cilium-etcd-operator"
    tag: "v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc"
--
  image:
    override: ~
    repository: "quay.io/cilium/operator"
    tag: "v1.12.0"
--
  image:
    override: ~
    repository: "quay.io/cilium/startup-script"
    tag: "d69851597ea019af980891a4628fb36b7880ec26"
--
  image:
    override: ~
    repository: "quay.io/cilium/cilium"
    tag: "v1.12.0"
--
    image:
      override: ~
      repository: "quay.io/cilium/clustermesh-apiserver"
      tag: "v1.12.0"
--
      image:
        override: ~
        repository: "quay.io/coreos/etcd"
        tag: "v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3"
```
failed logs
```
# sealos build -f Dockerfile -t registry.cn-shenzhen.aliyuncs.com/cnmirror/cilium:v1.12.0 .
2022-08-02 09:55:32 [INFO] srcPath: charts
2022-08-02 09:55:32 [INFO] srcPath is empty charts
2022-08-02 09:55:32 [INFO] fetch chart images: []
2022-08-02 09:55:32 [INFO] srcPath is empty manifests
2022-08-02 09:55:32 [INFO] fetch manifests images: []
2022-08-02 09:55:32 [WARN] if you access private registry,you must be 'sealos login' or 'buildah login'
2022-08-02 09:55:32 [INFO] pull images [quay.io/cilium/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd quay.io/cilium/hubble-relay:v1.12.0 quay.io/cilium/hubble-ui-backend:v0.9.0@sha256:000df6b76719f607a9edefb9af94dfd1811a6f1b6a8a9c537cba90bf12df474b quay.io/cilium/hubble-ui:v0.9.0@sha256:0ef04e9a29212925da6bdfd0ba5b581765e41a01f1cc30563cef9b30b457fea0 quay.io/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc quay.io/cilium/operator:v1.12.0 quay.io/cilium/startup-script:d69851597ea019af980891a4628fb36b7880ec26 quay.io/cilium/cilium:v1.12.0 quay.io/cilium/clustermesh-apiserver:v1.12.0 quay.io/coreos/etcd:v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3] for platform is linux/amd64
Pulling image: quay.io/cilium/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd
Pulling image: quay.io/cilium/hubble-relay:v1.12.0
Pulling image: quay.io/cilium/hubble-ui-backend:v0.9.0@sha256:000df6b76719f607a9edefb9af94dfd1811a6f1b6a8a9c537cba90bf12df474b
Pulling image: quay.io/cilium/hubble-ui:v0.9.0@sha256:0ef04e9a29212925da6bdfd0ba5b581765e41a01f1cc30563cef9b30b457fea0
Pulling image: quay.io/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
Pulling image: quay.io/cilium/operator:v1.12.0
Pulling image: quay.io/cilium/startup-script:d69851597ea019af980891a4628fb36b7880ec26
Pulling image: quay.io/cilium/cilium:v1.12.0
Pulling image: quay.io/cilium/clustermesh-apiserver:v1.12.0
Pulling image: quay.io/coreos/etcd:v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3
454886caa1bc: already exists 
aad27cebddd7: already exists 
f611ca99c216: already exists 
cc935e6c9491: already exists 
cb486e21b9dc: already exists 
2022-08-02 09:55:36 [WARN] save domain quay.io image quay.io/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc error: get cilium/cilium-etcd-operator tag descriptor error: filesystem: invalid path: /docker/registry/v2/repositories/cilium/cilium-etcd-operator/_manifests/tags/v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc/current/link, try "sealos login" if you are using a private registry
2022-08-02 09:55:36 [WARN] save domain quay.io image quay.io/cilium/hubble-ui:v0.9.0@sha256:0ef04e9a29212925da6bdfd0ba5b581765e41a01f1cc30563cef9b30b457fea0 error: get cilium/hubble-ui tag descriptor error: filesystem: invalid path: /docker/registry/v2/repositories/cilium/hubble-ui/_manifests/tags/v0.9.0@sha256:0ef04e9a29212925da6bdfd0ba5b581765e41a01f1cc30563cef9b30b457fea0/current/link, try "sealos login" if you are using a private registry
2022-08-02 09:55:37 [WARN] save domain quay.io image quay.io/cilium/hubble-ui-backend:v0.9.0@sha256:000df6b76719f607a9edefb9af94dfd1811a6f1b6a8a9c537cba90bf12df474b error: get cilium/hubble-ui-backend tag descriptor error: filesystem: invalid path: /docker/registry/v2/repositories/cilium/hubble-ui-backend/_manifests/tags/v0.9.0@sha256:000df6b76719f607a9edefb9af94dfd1811a6f1b6a8a9c537cba90bf12df474b/current/link, try "sealos login" if you are using a private registry
e3c63824251f: already exists 
b0f9b84c9530: already exists 
898baf1fd6d6: already exists 
d8cc641664e1: already exists 
4a5307b274d0: already exists 
143906c45a8f: already exists 
9b4c4e908f09: already exists 
76fdfa655b98: already exists 
4e477a7752f5: already exists 
dcd3b8736950: already exists 
8d936c9bfdfc: already exists 
70b398e3ae83: already exists 
c6c4f1b0ed0c: already exists 
2022-08-02 09:55:40 [WARN] save domain quay.io image quay.io/cilium/certgen:v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd error: get cilium/certgen tag descriptor error: filesystem: invalid path: /docker/registry/v2/repositories/cilium/certgen/_manifests/tags/v0.1.8@sha256:4a456552a5f192992a6edcec2febb1c54870d665173a33dc7d876129b199ddbd/current/link, try "sealos login" if you are using a private registry
534f4b5bc2da: already exists 
22496e146b8c: already exists 
40484c0a7634: already exists 
99384cb75682: already exists 
eac1c0663378: already exists 
68413ce8a529: already exists 
492da6231304: already exists 
75d8c87dfd66: already exists 
2022-08-02 09:55:42 [WARN] save domain quay.io image quay.io/coreos/etcd:v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3 error: get coreos/etcd tag descriptor error: filesystem: invalid path: /docker/registry/v2/repositories/coreos/etcd/_manifests/tags/v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3/current/link, try "sealos login" if you are using a private registry
Status: images save success
2022-08-02 09:55:42 [INFO] output images [quay.io/cilium/hubble-relay:v1.12.0 quay.io/cilium/operator:v1.12.0 quay.io/cilium/startup-script:d69851597ea019af980891a4628fb36b7880ec26 quay.io/cilium/clustermesh-apiserver:v1.12.0 quay.io/cilium/cilium:v1.12.0] for platform is linux/amd64
STEP 1/3: FROM scratch
STEP 2/3: COPY . .
STEP 3/3: CMD ["helm install cilium cilium --version 1.12.0 --namespace kube-system"]
COMMIT registry.cn-shenzhen.aliyuncs.com/cnmirror/cilium:v1.12.0
Getting image source signatures
Copying blob 21e7ef48fe9e done  
Copying config 4783062dad done  
Writing manifest to image destination
Storing signatures
--> 4783062dad1
Successfully tagged registry.cn-shenzhen.aliyuncs.com/cnmirror/cilium:v1.12.0
4783062dad16ca80bd7cff2f3fe51c5d2912ca33ccd75e1b9ecbeeef7f379bd8
2022-08-02 09:55:46 [INFO] 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos

```

**Detailed description of the feature**
support build image have digests

**If you have solution，please describe it**
support build image have digests
