### ISSUE TITLE
feature: read and render clusterfile with env or go-template

### ISSUE THREAD

**Issue by fengxsong** [labring/sealos#1480]
For example, when we use `sealos apply -f Clusterfile` command to create a new cluster, we must specified SSH username and password/public key in the `.spec.ssh` section,  what I suggest is that this can be done by configuring the environment variables before `sealos apply` and then sealos will auto render clusterfile with env.

#### Clusterfile

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  ...
  ssh:
    passwd: ${SSH_PASSWD:-s3cret}
    pk: ${SSH_PK:-~/.ssh/id_rsa}
    user: ${SSH_USER:-root}
```

#### usage

```
$ export SSH_USER=ubuntu SSH_PASSWD=nopassword
$ sealos apply -f Clusterfile
```
pretty simple...

#### Clusterfile

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  ...
  ssh:
    passwd: {{ env "SSH_PASSWD" }}
    pk: {{ default "~/.ssh/id_rsa" (env "SSH_PK") }}
    port: {{ default "22" (env "SSH_PK") | int }}
    user: {{ default "root" .Values.sshUser }}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: {{ default "cluster.local" .Values.dnsDomain }}
  serviceSubnet: {{ default "10.96.0.0/18" .Values.serviceSubnet }}
  podSubnet: {{ default "100.64.0.0/17" .Values.podSubnet }}
```

#### usage

```
$ cat values.yaml
sshUser: ubuntu
dnsDomain: testcluster.local
podSubnet: 10.244.0.0/12
serviceSubnet: 10.96.0.0/16
$ sealos apply -f Clusterfile --values values.yaml --set xxx=xxx --set yyy=yyy
```

this option offers more flexible composition capabilities.
`helm` drops `env`/`expandenv` template function because some security reasons, so do we also need to disable those two function and just pass a customize values file?
