### ISSUE TITLE
BUG: build longhorn images  find not exsits image

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1483]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/4150905/183232535-b1c44268-08a5-4911-abd3-cba741a03ab4.png">

https://github.com/labring/cluster-image/runs/7701453147?check_suite_focus=true

way pull image docker.io/library/:latest ???

**Comment by fanux** [comment]
helm template ....|grep image:

**Comment by willzhang** [comment]
```
root@ubuntu:/data/git/cluster-image/applications/longhorn/v1.3.0# helm template charts/longhorn |grep image:
              image:
              image:
              image:
              image:
        image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
          image: longhornio/longhorn-manager:v1.3.0
          image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-ui:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
        image: longhornio/longhorn-manager:v1.3.0
```

all templates here:

https://gist.github.com/willzhang/667dcf141c1bcb00e0180d8d16ad0142
