### ISSUE TITLE
Feature: metering controller

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1514]
Count every namespace resource usage every hour/day/month.

```
Spec:
    namespace string
    owner fanux
    []{
        resource [string]resource.Quantity
        timestap string
        timeInterval 1.5h
        Settled true
    }
```

**Comment by fanux** [comment]
https://calendly.com/fhtjob/sealos @SignorMercurio you can make an appointment with me to discuss the implementation of this controller

**Comment by fanux** [comment]
Using kubernetes Resource Quota feature

**Comment by fanux** [comment]
https://kubernetes.io/zh-cn/docs/concepts/policy/resource-quotas/  The resource quotas feature will count resource in namespace

**Comment by xiao-jay** [comment]
maybe this yaml is better？
```
apiVersion: v1
kind: Metering
metadata:
  name: xxxx
Spec:
//可以一次性设置多个角色的资源限制
    []{  
    	owner fanux //必填,基于role的RBAC
    	namespace [""," "] //必填，需要统计的namespace
        resources map[string]resource.Quantity //资源类型，必填
        timestap string //时间戳，用于记录上次统计时间
        timeInterval */1 * * * *  //使用cron形式，不设置的话默认是统计每小时/天/月的使用量
        isSettled true //是否已经结算
    }

**Comment by xiao-jay** [comment]
问题：
1、namespace字段是否要填在metadata字段下面

```
apiVersion: v1
kind: Metering
metadata:
  name: xxxx
  namespace: test //必填，需要统计的namespace
Spec:

    	
```



因为如果在spec字段下面的话，我apply -f yaml文件，metering在default namespace，quota在test namesapce。

2、计费的形式不是很清楚

计费是计算used还是计算分配（Hard）的？



然后全新开始经过一小时了使用了以下的资源

```
Name:            metering-sample
Namespace:       default
Resource         Used  Hard
--------         ----  ----
limits.cpu       1       1
limits.memory    1Gi     1Gi
requests.cpu     10m     1
requests.memory  10m     1Gi
```

要是过了10小时，计算使用的资源应该是10次每小时使用的资源总和吗，就比如使用的cpu资源是10m*10？

对计费模块具体表示不是很熟悉。

**Comment by xiao-jay** [comment]
final metering struct
```
apiVersion: v1
kind: Metering
metadata:
  name: xxxx
Spec:
    	owner: fanux //必填,基于role的RBAC
    	namespace: string //必填，需要统计的namespace
        resources: map[string]resource.Quantity //资源类型，必填
        timeInterval :*/1 * * * *  //默认不需要设置，使用cron形式，不设置的话默认是统计每小时/天/月的使用量
        list []{
             resources: map[string]resource.Quantity //如果改变了限制的资源类型，第一次会在这边写出来方便看限制资源的改变，默认为空
             timestap: string //时间戳，用于记录上次统计时间
             amount int     // 需要支付的金额
             isSettled:  true //是否已经结算
        }
        
        
        

```
