### ISSUE TITLE
Feature: Auto correct commits by `gofmt` and `goimports`

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1515]
We can use github actions to correct commit using `gofmt` and `goimports` and auto commit it.

Use this: https://github.com/stefanzweifel/git-auto-commit-action

```yaml
 - name: Format
        run: make format

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(fmt): format code'
```
