### ISSUE TITLE
Feature: Allows adding custom containerd configuration

### ISSUE THREAD

**Issue by myselfghost** [labring/sealos#1552]
**Which command or component**

sealos run 
When we are installing a cluster

**Detailed description of the feature**
1. Sometimes we may need to modify or add the configuration of containerd on all nodes When we are installing a cluster

**Comment by cuisongliu** [comment]
At present, it supports modifying the data directory to use environment variables.`ENV criData=/var/lib/containerd`

If you want to modify more parameters, you can overwrite the configuration with config.

**Comment by fanux** [comment]
@cuisongliu How? I think we need to add docs about how to custom containerd config

**Comment by cuisongliu** [comment]
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: xxxx
  ...
---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: mysql-config
spec:
  strategy: override
  path: etc/mysql-config.yaml
  data: |
       mysql-user: root
       mysql-passwd: xxx
```

we need add docs how to using config module
