### ISSUE TITLE
BUG: 在host1上安装多master集群后，在另外一个master机器上删除集群时脚本路径找不到

### ISSUE THREAD

**Issue by henryhyang** [labring/sealos#1640]
1. 有3台机器：master 10.161.30.251和10.161.30.112，node为10.161.30.253，在master 10.161.30.251上安装k8s集群，Cluster文件如下：
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 10.161.30.251
    - 10.161.30.112
    roles:
    - master
    - amd64
  - ips:
    - 10.161.30.253
    roles:
    - node
    - amd64
  image:
  - localhost/kubernetes:v1.24.3
  - localhost/calico:v3.22.1
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status: {}
```
3. k8s集群安装成功后，如果在master 10.161.30.251上卸载集群，能够成功。
但是如果在另一个master 10.161.30.112上卸载，提示脚本找不到，例如：
```
[10.161.30.112:22] run CmdAsync: clean.sh
10.161.30.112:22: bash: clean.sh: command not found
2022-08-26 14:22:29 [EROR] exec clean.sh failed failed to execute command(clean.sh) on host(10.161.30.112:22): output(bash: clean.sh: command not found), error(Process exited with status 127)
```
4. 作为master，在哪个master上执行操作都是一样的，希望修复这个问题，Thank you。

```
**Operating environment**

Kubernetes version: 1.24.3
Sealos version: v4.0.0
Operating system: Linux 3.10.0-1160.45.1.el7.x86_64 https://github.com/labring/sealos/issues/1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Runtime environment: vm (32G memory, 8 core cpu, 200G storage)
Cluster size: 2 master, 1 node
Additional information: none
```
