### ISSUE TITLE
自制集群镜像使用.tmpl模板时无法正常run

### ISSUE THREAD

**Issue by itzhoujun** [labring/sealos#1724]
## Which command or component

sealos run local-path-provisioner:v0.0.22

## The Description of the bug

local-path-provisioner是我自制的集群镜像，manifests下有local-path-storage.yaml.tmpl模板文件，使用了变量如下：
<img width="383" alt="image" src="https://user-images.githubusercontent.com/6897671/188827008-96943e0e-1c1b-4c86-98f9-8405965c4072.png">
Kubefile文件如下：
```
FROM scratch
COPY . .

ENV reclaimPolicy=Delete

CMD ["kubectl apply -f manifests/local-path-storage.yaml"]
```

## How to reproduce
打包镜像之后，执行sealos run local-path-provisioner:v0.0.22，没有报错，但实际pod没运行
![image](https://user-images.githubusercontent.com/6897671/188827584-f0d3282d-4f20-40c0-9122-f950adc95438.png)

如果不用模板变量，可以run成功：
![image](https://user-images.githubusercontent.com/6897671/188827825-3dbf6288-a2c2-486c-85f7-285d3d863470.png)

## Operating environment

- Kubernetes version: v1.24.3
- Sealos version: v4.1.3
- Operating system: ubuntu16.04

**Comment by cuisongliu** [comment]
local-path-storage.yaml.tmpl 发一下配置

**Comment by itzhoujun** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "persistentvolumeclaims", "configmaps" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "persistentvolumes", "pods" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.22
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .reclaimPolicy }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/local-path-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent



```
