### ISSUE TITLE
Question: metering question help

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos#1741]
Metering crd code：https://github.com/xiao-jay/sealos/tree/main/controllers/metering

1、i apply -f metering.yaml
```
apiVersion: metering.sealos.io/v1
kind: Metering
metadata:
  name: metering-sample
spec:
  namespace: ["default"]
  resourceQuota:
     resources:
      requests.cpu: "16"
      requests.memory: 200Gi
      limits.cpu: "16"
      limits.memory: 200Gi
```

2、➜  samples git:(main) $:  kubectl describe quota
```
Name:            metering-sample
Namespace:       default
Resource         Used  Hard
--------         ----  ----
limits.cpu       0     16
limits.memory    0     200Gi
requests.cpu     0     16
requests.memory  0     200Gi
```

3、i want to apply a pod
$ kubctl apply -f test_pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: default
spec:

  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "8"
          memory: 100Gi
        requests:
          cpu: "8"
          memory: 100Gi

```
#### Finally i get an error 
```
Error from server (Forbidden): error when creating "test_pod.yaml": pods "static-web" is forbidden: failed quota: metering-sample: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

please teach me is it the yaml file error or code error！

**Comment by cuisongliu** [comment]
default namespace has other resource ? quota must set request and limit for all resource .

**Comment by cuisongliu** [comment]
default namespace has other resource ? quota must set request and limit for all resource .

**Comment by xiao-jay** [comment]
i create a new namespace test,and apply quota and pod ,also get same error
```
➜  samples git:(main) ✗ kubectl apply -f metering_v1_metering.yaml -n test
metering.metering.sealos.io/metering-sample configured
➜  samples git:(main) ✗ kubectl describe quota -n test              
Name:            metering-sample
Namespace:       test
Resource         Used  Hard
--------         ----  ----
limits.cpu       0     16
limits.memory    0     200Gi
requests.cpu     0     16
requests.memory  0     200Gi

➜  samples git:(main) ✗ k apply -f test_pod.yaml -n test            
Error from server (Forbidden): error when creating "test_pod.yaml": pods "static-web" is forbidden: failed quota: metering-sample: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

➜  samples git:(main) ✗ k get pods -n test
No resources found in test namespace.
➜  samples git:(main) ✗ k get deployment -n test
No resources found in test namespace.
➜  samples git:(main) ✗ k get svc -n test       
No resources found in test namespace.

```

**Comment by cuisongliu** [comment]
```
resources:
        limits:
          cpu: "8"
          memory: 100Gi
        requests:
          cpu: "8"
          memory: 100Gi
```
change to 
```
resources:
        limits:
          cpu: "8"
          memory: 100Gi
        requests:
          cpu: "10m"
          memory: 10Mi
```
