### ISSUE TITLE
BUG: generate Clusterfile on arm host role is amd64

### ISSUE THREAD

**Issue by fanux** [labring/sealos#1787]
```
root@ecs-3e5b-0005:~# cat .sealos/default/Clusterfile
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2022-09-22T07:11:26Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.0.165:22
    - 192.168.0.82:22
    - 192.168.0.188:22
    roles:
    - master
    - amd64
```
