### ISSUE TITLE
BUG: user controller permission problem

### ISSUE THREAD

**Issue by Abingcbc** [labring/sealos#1795]
1. sealos run docker.io/labring/user-controller:dev
2. kubectl apply -f test.yaml
```
apiVersion: user.sealos.io/v1
kind: User
metadata:
  name: f8699ded-58d3-432b-a9ff-56568b57a38d
  labels:
    updateTime:  xxxx
spec:
  csrExpirationSeconds: 1000000000
```
User controller lack permissions.
![image](https://user-images.githubusercontent.com/34068205/192139401-ca93228a-c2fd-460f-a8c7-89775137ae54.png)

But after I manually add permissions to `clusterrole`, it raises another error.
![image](https://user-images.githubusercontent.com/34068205/192139458-bed95f29-b4bb-484e-99f0-821018a22c9c.png)
