### ISSUE TITLE
Feature: Image & App hub

### ISSUE THREAD

**Issue by lingdie** [labring/sealos#1902]
# imagehub
imagehub旨在sealos及sealos cloud上为用户提供类似于dockerhub的镜像管理工具，同时为apphub提供image matedate信息。

## 功能拆分
在sealos cloud及sealos命令行上提供image hub功能
* p0 image hub基本展示和CRUD功能
  * p0 baseInfo及用户提供的detailInfo展示
  * p0 支持搜索，优先级：repo name、keyword
  * p1 按最后上传时间为每一个repo维护一个latest标签的image
  * p2 支持cloud UI上增加image，提供一个页面方便用户添加image及DetailInfo
  * p2 基于上一功能，支持cloud上基于某一个image原本info修改image info
  * P2 applyCRD时 用户没有提供的信息比如 imageID/imageArch，~~通过buildah获取到镜像信息~~
* p0 支持sealos push image基于image中的文件生成imageDetailInfo
* p1 支持imageCRD增删时边界情况下的RepoCRD的增删
* p1 支持org创建、共享，支持对creator与binding的user提供pull/push权限，其他提供pull权限；即org<->user为n对n关系
* p2 image兼容: 在镜像本身没有README.md时, 支持 sealos push image -o README.md解析，不需要开发者重新构建镜像
* p2 sealos search镜像,可以使用registry的_catalog接口实现（待讨论）?

### CRD 结构设计与定义
仿照docker hub的结构设计，以sealos push labring/mysql-op:v1为例

**Org向上实现租户权限控制(通过k8s binding及准入控制), 向下保存repository集合**
- "labring" Organization Org
  - repositry list

Org CRD sample
```yaml
```

**Repo维护image tag list，需要支持image增删时自动判断是否为空/存在进行删除创建**

- "mysql-op" Repositry Repo
  - tags list

**Img保存镜像baseInfo和detailInfo，在sealos push时会读取镜像中的文件加载detailInfo，在集群CMD中新增ImgCRD则需要用户自定义**
- "labring/mysql-op:v1" Image Img
  - baseInfo
    - name: org + repo + tag
  - detailInfo
    * docs: md file.
    * keywords: srting list. 在imagehub中做search用，需要加入到lable中
    * icon: url. 目前仅支持公网URL，默认icon在前端支持
    * Description: string.
    * URL: url.
    * id: buildah inspect.
    * arch: buildah inspect.

Img CRD sample
```yaml
```

### webhook & etc
todo

### 镜像文件获取
- 在sealos push时获取，具体参考sealos push时mount和merge操作

### 镜像README.md约定
- 约定README.md放在操作系统根目录下面

README.md seample
```yaml
```

# 用户使用sealos image hub 流程
- 登录注册cloud
- 查看hub token or pw
- 用户命令行执行: sealos login hub.sealos.io -u -p or -token
  - 下载kubeconf到${workdir}/.sealos/
- sealos push
  - 解析image中的README.md, 获取img detail
  - client-go使用kubeconf添加img crd
- 发散
  - sealos search镜像
  - image兼容: 在镜像本身没有README.md时, 支持 sealos push image -o README.md解析

**Comment by lingdie** [comment]
Problems to solve:
- Image information that the user needs to enter
  - name: string type. required.
  - tag list: at least one required.
  - type: image type.
  - description: string type.
  - icon: get by url? default icon url?
  - docs: markdown document? When adding an image, if the file is long, it is not user-friendly.
  - etc...
- How to get image by image name & tag? 
- Documents and descriptions need to be synchronized with the image name or with the image tag?

**Comment by zzjin** [comment]
For image meta info, we can just read image‘s README.md(if provided), and can following metablock as below:

@see https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

Demo:

```markdown
---
title:  mysql-operator
author:
- mysql
- labring
keywords: [database, operator]
icon: https://icons8.com/icon/jYQqxG8eyJ19/external-mysql-programming-and-development-those-icons-lineal-color-those-icons
description: |
  This is the description.

  It consists of two paragraphs.

# I am image Title
```

**Comment by lingdie** [comment]
```
apiVersion: image.sealos.io/v1
kind: Image
metadata:
  name: image-sample
spec:
  imageBaseInfo:
    name: labring/mysql-operator
    tags: [latest, 8.0.23-14.1]
status: #gen at apply
  imageDetailInfoMap:
    latest:
      imageBaseInfo:
        url: www.google.com
        keywords: [database, operator]
        icon: https://icons8.com/icon/jYQqxG8eyJ19/external-mysql-programming-and-development-those-icons-lineal-color-those-icons
        description: mysql image description
        docs: mysql image docs
```

**Comment by lingdie** [comment]
> 



> 

```bash
# kubectl describe image image-sample                                                                                                                                                                                        [9:13:12]
Name:         image-sample
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  image.sealos.io/v1
Kind:         Image
Metadata:
  Creation Timestamp:  2022-10-19T09:13:12Z
  Generation:          1
  Managed Fields:
    API Version:  image.sealos.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:imageBaseInfo:
          .:
          f:name:
          f:tags:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-19T09:13:12Z
    API Version:  image.sealos.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:imageDetailInfoMap:
          .:
          f:8.0.23-14.1:
            .:
            f:description:
            f:docs:
            f:icon:
            f:keywords:
            f:url:
          f:latest:
            .:
            f:description:
            f:docs:
            f:icon:
            f:keywords:
            f:url:
    Manager:         main
    Operation:       Update
    Subresource:     status
    Time:            2022-10-19T09:13:12Z
  Resource Version:  805623
  UID:               58d73607-8b52-4b6d-aa20-3fc49ca70cee
Spec:
  Image Base Info:
    Name:  labring/mysql-operator
    Tags:
      latest
      8.0.23-14.1
Status:
  Image Detail Info Map:
    8.0.23-14.1:
      Description:  description
      Docs:         docs
      Icon:         https://icons8.com/icon/jYQqxG8eyJ19/external-mysql-programming-and-development-those-icons-lineal-color-those-icons
      Keywords:
        database
        operator
      URL:  www.mysql.com
    Latest:
      Description:  description
      Docs:         docs
      Icon:         https://icons8.com/icon/jYQqxG8eyJ19/external-mysql-programming-and-development-those-icons-lineal-color-those-icons
      Keywords:
        database
        operator
      URL:  www.mysql.com
Events:     <none>
```

**Comment by zzjin** [comment]
> ```yaml
>  tags: [latest, 8.0.23-14.1]
> ```
IMO, the `tag` label can contain one and only one name, just like docker-hub, so users can apply multiple crds with different tag name(same will update).

**Comment by lingdie** [comment]
ref to design docs: https://github.com/lingdie/sealos/blob/feature_imagehub/docs/4.0/docs/design/imagehub.md

**Comment by zzjin** [comment]
### AppStore data request 

### Info spec
1. minimal info:  
    > name *"labring/mysql:latest"*
2. grid info:  
    > icon *"https://mysql.icon"*  
    > name *"mysql"*  
    > category *"database"*  
    > rating *"30000"*  
    > author_icon *"https://mysql-author.icon"*  
3. detail info: 
    > full detailed info like above detail data

### Page spec

1. Index page:
    1. Show featured images, using grid info (P2)
2. List page:
    1. Show all images, using grid info (P1)
    2. Show images with page split, using grid info (P2)
3. image detail page
    1. Show image detail without tag, using detail info (P1)
    2. Change image tags, using detail info (P1)
    2. Comments (P2)
    3. Ratings (P2)
4. organization detail page
    1. Show images under org, using grid info (P1)
    2. ORG detail info (P2)

**Comment by zzjin** [comment]
```yaml
# getcrd 1
apiVersion: imagehub.sealos.io/v1
kind: Repository
metadata:

spec:
 - labring.mysql
 - yy.helm

---
# getcrd 2
apiVersion: imagehub.sealos.io/v1
kind: ImagePack
metadata:
  type: grid
  names: 
  - labring/mysql:latest
  - yy/helm:v8.0.25

spec:
  - name: labring/mysql:latest
    detail:
```

```yaml
# getcrd detail image all tags

apiVersion: imagehub.sealos.io/v1
kind: Repository
metadata:
  name: labring.mysql

spec: 
  tags: [v8.0.5, v8.0.4]

--- 
# getcrd detail image detail info
apiVersion: imagehub.sealos.io/v1
kind: ImagePack
metadata:
  type: detail 
  names: 
  - labring/mysql:v8.0.5
  - yy/helm:v8.0.25

spec:
  - data:

```
