### ISSUE TITLE
Feature: sync dockerhub  cloud image to aliyun registry

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#1923]
**Which command or component**

eg.  cloud image

**Detailed description of the feature**

Aliyun registry will be very fast for image pull, so should we sync dockerhub cloud images to aliyun registry, give user a Second pull option？

Cloud image have subimage ,so it usually bigger, it's hard to pull.

**If you have solution，please describe it**

there have a simple solution ,use github action to schedule

.github/workflows/main.yml
```
name: image-sync
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 14 * * 1'

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: check podman
      run: |
        sudo podman version
    - name: sync images
      run: |
        sudo podman run -it --rm -v ${PWD}:/workspace -w /workspace quay.io/skopeo/stable:latest \
        sync --src yaml --dest docker sync.yaml registry.cn-shenzhen.aliyuncs.com/labring \
        --dest-username $USERNAME --dest-password $PASSWORD \
        --keep-going --retry-times 2
```
sync.yaml 
```
docker.io:
    images:
        labring/nginx: []
        labring/tomcat: []
```

it will be like this

![image-sync.png](https://s2.loli.net/2022/10/20/7zn3MFi2TyISxrc.png)
