### ISSUE TITLE
Question: 新增节点会改变Clusterfile

### ISSUE THREAD

**Issue by rechardwang** [labring/sealos#2040]
### Detailed description of the question.

使用命令进行节点的新增 sealos add --nodes 10.0.210.61 发现自动把 /root/.sealos/default/Clusterfile 里面 calico 配置给删掉了

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2022-11-04T08:54:25Z"
  name: default
spec:
  hosts:
  - ips:
    - 10.0.210.57:22
    - 10.0.210.58:22
    - 10.0.210.59:22
    roles:
    - master
    - amd64
  - ips:
    - 10.0.210.60:22
    roles:
    - node
    - amd64
  - ips:
    - 10.0.210.61:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.6
  - labring/helm:v3.8.2
  - labring/calico:v3.24.1
  ssh:
    passwd: ******
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status:
  conditions:
  - lastHeartbeatTime: "2022-11-04T09:55:33Z"
    message: Applied to cluster successfully
    reason: Ready
    status: "True"
    type: ApplyClusterSuccess
  mounts:
  - env:
      criData: /var/lib/containerd
      disableApparmor: "false"
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
    imageName: labring/kubernetes:v1.24.6
    labels:
      auth: auth.sh
      check: check.sh $registryData
      clean: clean.sh $criData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v4.1.3
      init: init.sh $registryDomain $registryPort
      init-registry: init-registry.sh $registryData $registryConfig
      io.buildah.version: 1.25.0-dev
      sealos.io.type: rootfs
      sealos.io.version: v1beta1
      version: v1.24.6
    mountPoint: /var/lib/containers/storage/overlay/73c907ba50e52ad1894b102f0a5575395cbe1308fcbd5df6fe08b06aeda07215/merged
    name: default-guvwjedh
    type: rootfs
  - cmd:
    - cp opt/helm /usr/bin/
    imageName: labring/helm:v3.8.2
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/3a57435e8a7de6b75e6da61fff6482369fdb5b0f732e110df1eb3489e98ecd5e/merged
    name: default-9t96yz0k
    type: application
  - cmd:
    - kubectl create namespace tigera-operator
    - helm install calico charts/calico --namespace tigera-operator
    imageName: labring/calico:v3.24.1
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/299bfd8bd14fd595e7afccd96a159e052c4410a1d4c3826468e5c0d62e9d6579/merged
    name: default-yuije3ud
    type: application
  phase: ClusterSuccess
```

我不确定有没有问题。

sealos执行add时版本为4.1.4rc 发现不成功之后立即查看了文件发现被删除，随后切换回了4.1.3进行添加成功之后 calico相关配置也没有回来
