### ISSUE TITLE
BUG: sealos run --env will remember the env all the time

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2046]
### Sealos Version

v4.1.4-rc1

### How to reproduce the bug?

1、cloud image Kubefile

```
FROM scratch

ENV CONT_IMG_VER=${CONT_IMG_VER:-v1.0.0}

CMD ["echo $(CONT_IMG_VER)"]
```

2、run app with v2.0.0
```
root@node1:~# sealos run -f registry.cn-shenzhen.aliyuncs.com/cnmirror/env:v1.0 --env CONT_IMG_VER=v2.0.0
2022-11-05T20:46:46 info start to install app in this cluster
are you sure to override these app? Yes [y/yes], No [n/no] : y
2022-11-05T20:46:48 info pulling images [registry.cn-shenzhen.aliyuncs.com/cnmirror/env:v1.0] for platform linux/amd64
64eb9204d4a0267da8585c7a74718d424b73178e3170506f14b0e88abf024e44
default-xpa2lcg9
2022-11-05T20:46:48 info guest cmd is echo v2.0.0
v2.0.0
2022-11-05T20:46:48 info succeeded install app in this cluster
2022-11-05T20:46:48 info no nodes that need to be scaled
2022-11-05T20:46:48 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos
                BuildVersion: 4.1.4-rc1-990b821d
```
run again without v2.0.0 , it still print v2.0.0
```
root@node1:~# sealos run -f registry.cn-shenzhen.aliyuncs.com/cnmirror/env:v1.0
2022-11-05T20:46:56 info start to install app in this cluster
are you sure to override these app? Yes [y/yes], No [n/no] : y
2022-11-05T20:46:58 info pulling images [registry.cn-shenzhen.aliyuncs.com/cnmirror/env:v1.0] for platform linux/amd64
64eb9204d4a0267da8585c7a74718d424b73178e3170506f14b0e88abf024e44
default-xpa2lcg9
2022-11-05T20:46:59 info guest cmd is echo v2.0.0
v2.0.0
2022-11-05T20:46:59 info succeeded install app in this cluster
2022-11-05T20:46:59 info no nodes that need to be scaled
2022-11-05T20:46:59 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website :https://www.sealos.io/
                  Address :github.com/labring/sealos
                BuildVersion: 4.1.4-rc1-990b821d

```

### What is the expected behavior?

at the second time i hope it print v1.0.0

### What do you see instead?

at the second time it still print v2.0.0

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system: ubuntu 22.04
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by willzhang** [comment]
Clusterfile should be update when run sealos run again
```
  - cmd:
    - helm upgrade -i gitea charts/gitea -n gitea --create-namespace --set gitea.admin.password=gitea_admin,service.http.type=NodePort,service.ssh.type=NodePort,service.http.nodePort=$(HTTP_NODE_PORT),service.ssh.nodePort=$(SSH_NODE_PORT),gitea.config.server.ROOT_URL=http://$(NODE_IP):$(HTTP_NODE_PORT),gitea.config.server.SSH_DOMAIN=${NODE_IP}:${SSH_NODE_PORT}
    env:
      HTTP_NODE_PORT: "30033"
      NODE_IP: git.example.com
      SSH_NODE_PORT: "30022"
    imageName: registry.cn-shenzhen.aliyuncs.com/cnmirror/gitea:v1.17.3
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /data/containers/storage/overlay/2450f020781d1b80961c6b083b38b323c6a873baef57d49d78e09f75ae3dad28/merged
    name: default-1kdf47zk
    type: application
```
