### ISSUE TITLE
Clusterfile template docs error

### ISSUE THREAD

**Issue by TinyWuP** [labring/sealos#2081]
### Sealos Version

V4.1.3

### How to reproduce the bug?

版本信息
sealos version 
{"gitVersion":"4.1.3","gitCommit":"b2ba9705","buildDate":"2022-09-06T06:04:14Z","goVersion":"go1.19","compiler":"gc","platform":"linux/amd64"}
使用模板来创建k8s集群（https://www.sealos.io/docs/cli/apply），配置如下

### cat Clusterfile.yaml 

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  hosts:
    - ips: {{ .Values.masters | toYaml | nindent 8 }}
      roles: ["master", "amd64"]
    {{- with .Values.nodes }}
    - ips: {{ . | toYaml | nindent 8 }}
      roles: ["node", "amd64"]
    {{- end }}
  image: {{ .Values.images | toYaml | nindent 4 }}
  ssh:
    passwd: {{ env "SSH_PASSWORD" .Values.ssh.passwd }}
    pk: {{ default "~/.ssh/id_rsa" .Values.ssh.pk }}
    port: {{ default 22 .Values.ssh.port | int }}
    user: {{ default "root" .Values.ssh.user }}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  dnsDomain: {{ default "cluster.local" .Values.networking.dnsDomain }}
  serviceSubnet: {{ default "10.96.0.0/18" .Values.networking.serviceSubnet }}
  podSubnet: {{ default "100.64.0.0/17" .Values.networking.podSubnet }}
```

### cat values.yaml 

```
clusterName: default
images:
  - dockerhub.tencentcloudcr.com/labring/kubernetes:v1.23.8
  - dockerhub.tencentcloudcr.com/labring/calico:v3.24.1
masters:
  - 10.10.0.120:22
nodes:
  - 10.10.0.121:22
  - 10.10.0.122:22
ssh:
  # passwd: notSetYet
  pk: /path/to/private/key/file
  port: 22
  user: root
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/18
  podSubnet: 100.64.0.0/17
```
安装后报错
### sealos apply -f Clusterfile.yaml --values values.yaml --set clusterName=tiny-k8s --env SSH_PASSWORD='xxxxxx' 
```
Error: template: goTpl:15:15: executing "goTpl" at <env>: wrong number of args for env: want 1 got 2
Usage:
  sealos apply [flags]

Examples:
sealos apply -f Clusterfile

Flags:
  -f, --Clusterfile string    apply a kubernetes cluster (default "Clusterfile")
      --config-file strings   path of custom config files, to use to replace the resource
      --env strings           environment variables to set during command execution
  -h, --help                  help for apply
      --set strings           set values on the command line
      --values strings        values file to apply into Clusterfile

Global Flags:
      --cluster-root string   cluster root directory (default "/var/lib/sealos")
      --debug                 enable debug logger

template: goTpl:15:15: executing "goTpl" at <env>: wrong number of args for env: want 1 got 2
```

### sealos apply -f Clusterfile.yaml --values values.yaml --set clusterName=tiny-k8s --env SSH_PASSWORD='xxxxxx' 
```
Error: template: goTpl:15:15: executing "goTpl" at <env>: wrong number of args for env: want 1 got 2
Usage:
  sealos apply [flags]

Examples:
sealos apply -f Clusterfile

Flags:
  -f, --Clusterfile string    apply a kubernetes cluster (default "Clusterfile")
      --config-file strings   path of custom config files, to use to replace the resource
      --env strings           environment variables to set during command execution
  -h, --help                  help for apply
      --set strings           set values on the command line
      --values strings        values file to apply into Clusterfile

Global Flags:
      --cluster-root string   cluster root directory (default "/var/lib/sealos")
      --debug                 enable debug logger

template: goTpl:15:15: executing "goTpl" at <env>: wrong number of args for env: want 1 got 2
```

### Operating environment

```markdown
- Sealos version:v4.1.3
- Docker version:none
- Kubernetes version:v1.23.8
- Operating system:CentOS Linux release 7.9.2009 (Core)
- Runtime environment:virtual machine (esxi, 4G memory, 2 core cpu, 20G storage)
- Cluster size:1 master， 2 node
- Additional information:none
```

**Comment by fengxsong** [comment]
```yaml
spec:
    ssh:
      passwd: {{ env "SSH_PASSWORD" .Values.ssh.passwd }}
```
template function `env` only accept one arg.
