### ISSUE TITLE
BUG:Apply twice will prompt that the kubelet port is occupied

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2140]
### Sealos Version

v4.1.3-rc1

### How to reproduce the bug?

![image](https://user-images.githubusercontent.com/8912557/203509914-2f358611-7bbe-4148-aa38-272403a5460f.png)

Apply twice will prompt that the kubelet port is occupied

Clusterfile:
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    - 192.168.0.2:22
    roles:
    - master
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.24.1
```

`sealos apply -f Clusterfile` twice.

### What is the expected behavior?

If the expected state is consistent with the actual state, ignore it directly. Can execute sealos apply multiple times
