### ISSUE TITLE
BUG: sealctl images panic

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2246]
### Sealos Version

v4.1.4-rc2

### How to reproduce the bug?

```
root@test-node-0:~# /var/lib/sealos/data/default/rootfs/opt/sealctl version
{"gitVersion":"4.1.4-rc2","gitCommit":"975627e5","buildDate":"2022-12-11T12:21:27Z","goVersion":"go1.19.3","compiler":"gc","platform":"linux/arm64"}
root@test-node-0:~# /var/lib/sealos/data/default/rootfs/opt/sealctl images
ERRO[0000] Failed to GetDriver graph overlay /var/lib/containers/storage
Error: failed to GetDriver graph overlay /var/lib/containers/storage: driver not supported
failed to GetDriver graph overlay /var/lib/containers/storage: driver not supported
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
```
project_name: sealos
#gomod:
#  # Proxy a module from proxy.golang.org, making the builds verifiable.
#  # This will only be effective if running against a tag. Snapshots will ignore this setting.
#  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
#  #
#  # Default is false.
#  proxy: true
#
#  # If proxy is true, use these environment variables when running `go mod` commands (namely, `go mod tidy`).
#  # Defaults to `os.Environ()`.
#  env:
#    - GOPROXY=https://goproxy.cn

before:
  hooks:
    - make clean
    - go mod tidy
builds:
  - id: sealos
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    main: ./cmd/sealos
    binary: sealos
    hooks:
      post: upx "{{ .Path }}"
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    tags:
      - containers_image_openpgp
      - netgo
      - exclude_graphdriver_devicemapper
      - static
      - osusergo
      - exclude_graphdriver_btrfs
    ldflags:
      - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      - -s -w
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        goarm: ""
        gomips: ""
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc

  - id: sealctl
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    main: ./cmd/sealctl
    hooks:
      post: upx "{{ .Path }}"
    binary: sealctl
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
      tags:
      - containers_image_openpgp
      - netgo
      - exclude_graphdriver_devicemapper
      - static
      - osusergo
      - exclude_graphdriver_btrfs
    ldflags:
      - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      - -s -w
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        goarm: ""
        gomips: ""
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc

  - id: lvscare
    env:
      - CGO_ENABLED=0
    main: ./cmd/lvscare
    hooks:
      post: upx "{{ .Path }}"
    binary: lvscare
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    tags:
      - containers_image_openpgp
      - netgo
      - exclude_graphdriver_devicemapper
      - static
      - osusergo
      - exclude_graphdriver_btrfs
    ldflags:
      - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      - -s -w

  - id: image-cri-shim
    env:
      - CGO_ENABLED=0
    main: ./cmd/image-cri-shim
    hooks:
      post: upx "{{ .Path }}"
    binary: image-cri-shim
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    tags:
      - containers_image_openpgp
      - netgo
      - exclude_graphdriver_devicemapper
      - static
      - osusergo
      - exclude_graphdriver_btrfs
    ldflags:
      - -X github.com/labring/sealos/pkg/version.gitVersion={{.Version}}
      - -X github.com/labring/sealos/pkg/version.gitCommit={{.ShortCommit}}
      - -X github.com/labring/sealos/pkg/version.buildDate={{.Date}}
      - -s -w

release:
#  github:
#    name: sealos
  prerelease: auto

dockers:
  - use: buildx
    ids:
      - lvscare
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/lvscare:{{ .Tag }}-amd64
    dockerfile: docker/lvscare/Dockerfile.release
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=io.sealos.image.created={{.Date}}
      - --label=io.sealos.image.title=lvscare
      - --label=io.sealos.image.revision={{.ShortCommit}}
      - --label=io.sealos.image.version={{.Tag }}
      - --label=io.sealos.image.auth={{ .Env.USERNAME }}
  - use: buildx
    ids:
      - lvscare
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/lvscare:{{ .Tag }}-arm64
    dockerfile: docker/lvscare/Dockerfile.release
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=io.sealos.image.created={{.Date}}
      - --label=io.sealos.image.title=lvscare
      - --label=io.sealos.image.revision={{.ShortCommit}}
      - --label=io.sealos.image.version={{.Tag }}
      - --label=io.sealos.image.auth={{ .Env.USERNAME }}
  - use: buildx
    ids:
      - sealos
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/sealos:{{ .Tag }}-amd64
    dockerfile: docker/sealos/Dockerfile.release
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=io.sealos.image.created={{.Date}}
      - --label=io.sealos.image.title=sealos
      - --label=io.sealos.image.revision={{.ShortCommit}}
      - --label=io.sealos.image.version={{.Tag }}
      - --label=io.sealos.image.auth={{ .Env.USERNAME }}
  - use: buildx
    ids:
      - sealos
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/sealos:{{ .Tag }}-arm64
    dockerfile: docker/sealos/Dockerfile.release
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=io.sealos.image.created={{.Date}}
      - --label=io.sealos.image.title=sealos
      - --label=io.sealos.image.revision={{.ShortCommit}}
      - --label=io.sealos.image.version={{.Tag }}
      - --label=io.sealos.image.auth={{ .Env.USERNAME }}
docker_manifests:
  - name_template: ghcr.io/{{ .Env.USERNAME }}/lvscare:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/lvscare:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.USERNAME }}/lvscare:{{ .Tag }}-arm64
  - name_template: ghcr.io/{{ .Env.USERNAME }}/sealos:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.USERNAME }}/sealos:{{ .Tag }}-amd64
      - ghcr.io/{{ .Env.USERNAME }}/sealos:{{ .Tag }}-arm64

nfpms:
  - id: packages
    builds:
      - sealos
    vendor: labring
    homepage: https://github.com/labring/sealos
    maintainer: fanux (https://github.com/fanux)
    description: Cloud OS distribution with Kubernetes as kernel
    license: Apache 2.0
    formats:
      - deb
      - rpm

publishers:
  - name: "fury.io"
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: |
      curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.USERNAME }}/

checksum:
  disable: true
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

```
