### ISSUE TITLE
Feature: sealos run --single should auto untaint master nodes

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2317]
### What is the problem this feature will solve?

after `sealos run --single` should do this everytime manaul
```
root@ubuntu:~# kubectl taint nodes --all node-role.kubernetes.io/master:NoSchedule-
node/ubuntu untainted
```

### If you have solution，please describe it

if sealos run --single

then
```
kubeadm init .... --skip-phases=mark-control-plane

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
skipPhases:
- mark-control-plane
```
or
```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  taints:
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io/master
```
