### ISSUE TITLE
BUG: using 4.1.5-alpha2 sealos version for infra exec error 

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2515]
### Sealos Version

cloud

### How to reproduce the bug?

```
apiVersion: infra.sealos.io/v1
kind: Infra
metadata:
  name: test-sealos
spec:
  hosts:
  - roles: [master] 
    count: 3
    flavor: t2.medium
    # ami-098549a3574f12db5 - arm 510
    # ami-04f581a700a8ff2de - arm 4.x
    # ami-056b2d99097e20983 - x86 4.x
    image: "ami-048280a00d5085dd1" # x86 510A
    disks:
    - capacity: 16
      volumeType: gp3
      # allowed value is root|data
      type: "root"

  - roles: [ node ] 
    count: 3 
    flavor: t2.medium
    image: "ami-048280a00d5085dd1"
    disks:
    - capacity: 16
      volumeType: gp3
      # allowed value is root|data
      type: "root"
---
apiVersion: cluster.sealos.io/v1
kind: Cluster
metadata:
  name: test-sealos
  annotations:
    sealos.io/sealos/version: "4.1.5-alpha2"
spec:
  infra: test-sealos
  image:
    - labring/kubernetes:v1.25.5
    - labring/calico:v3.24.1  

```

```
The Cluster "test-sealos" is invalid: metadata.annotations: Invalid value: "sealos.io/sealos/version": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')

```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```
