### ISSUE TITLE
BUG: docs error

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos#2570]
### Sealos Version

root@sealos-cluster1:/var/lib/sealos/data/default/rootfs# sealos version {"gitVersion":"untagged","gitCommit":"90494032","buildDate":"2023-01-30T14:56:10+0000","goVersion":"go1.19.2","compiler":"gc","platform":"linux/amd64"}

### How to reproduce the bug?

docs  https://www.sealos.io/zh-Hans/docs/build-cloud-image/build-cloudImage-with-env
```
root@sealos-cluster1:/var/lib/sealos/data/default/rootfs# sealos run labring/nginx:v1.23.1 --env serviceType=LoadBalancer --env http_NodePort=30080 --env https_NodePort=30443
Error: master ip(s) must specified
master ip(s) must specified
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by xiao-jay** [comment]
i think is the image problem
```
root@sealos-cluster1:/home/sealos# sealos run labring/nginx:v1.23.1 --env serviceType=LoadBalancer --env http_NodePort=30080 --env https_NodePort=30443
Error: master ip(s) must specified
master ip(s) must specified
root@sealos-cluster1:/home/sealos# sealos version
{"gitVersion":"untagged","gitCommit":"90494032","buildDate":"2023-01-30T14:56:10+0000","goVersion":"go1.19.2","compiler":"gc","platform":"linux/amd64"}
```

**Comment by cuisongliu** [comment]
sealos run --env serviceType=LoadBalancer --env http_NodePort=30080 --env https_NodePort=30443 labring/nginx:v1.23.1

try it.

**Comment by xiao-jay** [comment]
```
root@sealos-cluster1:/home/sealos# sealos run --env serviceType=LoadBalancer --env http_NodePort=30080 --env https_NodePort=30443 labring/nginx:v1.23.1
Error: master ip(s) must specified
master ip(s) must specified
```
same problem

**Comment by cuisongliu** [comment]
cat Clusterfile

**Comment by xiao-jay** [comment]
```
root@sealos-cluster1:/home/sealos/.sealos/default# ls
Clusterfile.1673429123
root@sealos-cluster1:/home/sealos/.sealos/default# cat Clusterfile.1673429123 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  deletionTimestamp: "2023-01-11T09:25:23Z"
  name: default
spec:
  ssh:
    pk: /home/sealos/.ssh/id_rsa
    port: 22
    user: root
status:
  mounts:
  - env:
      criData: /var/lib/containerd
      defaultVIP: 10.103.97.2
      disableApparmor: "false"
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
      sandboxImage: pause:3.8
    imageName: docker.io/labring/kubernetes:v1.25.0
    labels:
      auth: auth.sh
      check: check.sh $registryData
      clean: clean.sh && bash clean-cri.sh $criData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v4.1.3
      init: init-cri.sh $registryDomain $registryPort && bash init.sh
      init-registry: init-registry.sh $registryData $registryConfig
      io.buildah.version: 1.25.0-dev
      org.opencontainers.image.description: kubernetes-v1.25.0 container image
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.source: https://github.com/labring-actions/cache
      sealos.io.type: rootfs
      sealos.io.version: v1beta1
      version: v1.25.0
      vip: $defaultVIP
    mountPoint: /var/lib/containers/storage/overlay/bdc078e70302476d98e0cb9f46b49ff630d5b615104ccdc45ebab176b8a7724e/merged
    name: default-9ga7mzd3
    type: rootfs
  - cmd:
    - cp opt/helm /usr/bin/
    imageName: docker.io/labring/helm:v3.8.2
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/1f8fb9ef99b809c959161f05413561373f4539271145bd7b4de58425ccbde761/merged
    name: default-6wj6fvqb
    type: application
  - cmd:
    - kubectl create namespace tigera-operator
    - helm install calico charts/calico --namespace tigera-operator
    imageName: docker.io/labring/calico:v3.24.1
    labels:
      io.buildah.version: 1.25.0-dev
    mountPoint: /var/lib/containers/storage/overlay/83bdf3c17fb732155905c952a05df3d3ff09c842d6f1391f7cc4c15b48ff8010/merged
    name: default-8tc9jzoj
    type: application
root@sealos-cluster1:~/.kube/cache# kubectl get nodes
NAME              STATUS   ROLES           AGE     VERSION
dai-master1       Ready    control-plane   7d18h   v1.25.6
dai-node1         Ready    <none>          7d18h   v1.25.6
sealos-cluster1   Ready    <none>          7d18h   v1.25.6
```
