### ISSUE TITLE
Feature: install cluster with the second network interface ip

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2594]
### What is the problem this feature will solve?

 cluster support use interface without default route.

i have two interface, i want use the second one, but it is impossible in sealos, because the second interface have no defalut route.
![8948e40731f899be57c1fefc7efc5ba](https://user-images.githubusercontent.com/33590311/219042153-b05abf35-a8ef-4eeb-853a-7b093561134e.png)

and one server only support one default route

![image](https://user-images.githubusercontent.com/33590311/219042486-24c78d0d-2056-4b52-8b68-d5349b3e79a0.png)

this config not effiect

![b9957bb6785ea5172e0417fb2cf709f](https://user-images.githubusercontent.com/33590311/219042566-280dec08-210f-47bd-9733-4e566487dc2f.png)

sealos will use the first interface ip all the time

![e168a22c5c1ba0a1752424dc9de968f](https://user-images.githubusercontent.com/33590311/219042656-d1b3500f-17d1-48a9-b6e7-15010bbba414.png)

### If you have solution，please describe it

add node-ip to kubeadm-init.yaml and kubeadm-join-node.yaml

```
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "${NODE_IP}"
```

or 
```
Environment="KUBELET_EXTRA_ARGS=--node-ip={{ .NodeIP }} --hostname-override={{ .Hostname }} {{ if .ContainerRuntime }}--network-plugin=cni{{ end }}"

```

**Comment by fanux** [comment]
So just use your own kubeadm config?

**Comment by willzhang** [comment]
> So just use your own kubeadm config?

There is no way to change ip to 192.168.70.32，because it have no default route.

**Comment by willzhang** [comment]
advertise-address is correct
```
root@node1:~# kubectl -n kube-system get pods kube-apiserver-unicom    -o yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 172.16.100.38:6443
    kubernetes.io/config.hash: 0b698ea9bc01fe67eeb595bfb761cc44
    kubernetes.io/config.mirror: 0b698ea9bc01fe67eeb595bfb761cc44
    kubernetes.io/config.seen: "2023-03-03T17:03:03.947654157+08:00"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-03-03T09:07:05Z"
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver-unicom
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: unicom
    uid: 4d627be5-69a3-4a8c-9467-bebb5d41625d
  resourceVersion: "3513231"
  uid: 8ca80f42-2586-4ba8-a3cb-6175ab8e742d
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.70.32
```

but kubectl get nodes is wrong
```
but
![image](https://user-images.githubusercontent.com/33590311/223960757-80a4f8bf-8767-4bdd-a83d-4b3bce20838c.png)

@hexinatgithub need help

**Comment by DeathInTheAir** [comment]
同问，双网卡，但是node 的ip （192.168.1.1/24）和我Clusterfile里的不一致（10.66.231.0/24），不过我的calico是正常的。pod 访问192.168.1.1不通。

**Comment by willzhang** [comment]
here have two interface, kubeadm init only use the first interface `ens160` ip, because it have a default gateway.
```
root@master:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:ad:51:dd brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 192.168.72.34/24 brd 192.168.72.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fead:51dd/64 scope link 
       valid_lft forever preferred_lft forever
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:ad:dd:6d brd ff:ff:ff:ff:ff:ff
    altname enp11s0
    inet 192.168.73.34/24 brd 192.168.73.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fead:dd6d/64 scope link 
       valid_lft forever preferred_lft forever
```
ens160 have `gateway4` 
```
root@master:~# cat /etc/netplan/00-installer-config.yaml 
# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      addresses:
      - 192.168.72.34/24
      gateway4: 192.168.72.8
      nameservers:
        addresses:
        - 114.114.114.114
        - 8.8.8.8
        search: []
    ens192:
      addresses:
      - 192.168.73.34/24
      nameservers:
        addresses:
        - 114.114.114.114
        - 8.8.8.8
        search: []
  version: 2
```
if i hope kubeadm use the second ip address, have two way:

1. delete ens160 gateway4 and config it in ens192
2. use `kubeadm init --apiserver-advertise-address` and `kubelet --node-ip` paramenter

Configuration of the method 2:

kubeadm-config-init.yaml
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "$INTERNALIP_ens192"
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "$INTERNALIP_ens192"
```
kubeadm-config-join.yaml
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "$INTERNALIP_ens192"
```
then
```
kubeadm init --config=kubeadm-config-init.yaml
kubeadm join --config=kubeadm-config-join.yaml
```
