### ISSUE TITLE
BUG: custom etcd external config not override the default ClusterConfiguration 

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2687]
### Sealos Version

v4.1.5

### How to reproduce the bug?

create clusterfile with external etcd
```
root@node34:~# cat Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.34:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
```
apply clusterfile
```
sealos apply -f Clusterfile
```
error log
```
...
I0301 00:57:24.719732 1943896 initconfiguration.go:254] loading configuration from "/root/.sealos/default/etc/kubeadm-init.yaml"
W0301 00:57:24.727226 1943896 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
W0301 00:57:24.727271 1943896 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
etcd: Invalid value: "": .Etcd.Local and .Etcd.External are mutually exclusive
2023-03-01T00:57:24 error Applied to cluster error: failed to init init master0 failed, error: exit status 3. Please clean and reinstall
2023-03-01T00:57:24 debug write cluster file to local storage: /root/.sealos/default/Clusterfile
Error: failed to init init master0 failed, error: exit status 3. Please clean and reinstall
```
Custom configuration and etcd default configuration exist at the same time
```
root@node34:~# cat /root/.sealos/default/etc/kubeadm-init.yaml
---
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
  local:
    dataDir: ""
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
```

### What is the expected behavior?

only have external config
```
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
```

### What do you see instead?

There are two conflicting configurations at the same time

```
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
  local:
    dataDir: ""
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by willzhang** [comment]
try rebuild kubernetes
```
mkdir -p /tmp/buildimage
cat > /tmp/buildimage/kubeadm.yml <<EOF 
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external: {}
EOF
cat > /tmp/buildimage/Kubefile <<EOF
FROM labring/kubernetes:v1.25.6
COPY kubeadm.yml etc/
EOF
sudo sealos build --debug -t registry.cn-shenzhen.aliyuncs.com/cnmirror/kubernetes:v1.25.6 /tmp/buildimage
```

```
root@node40:~# cat Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.40:22
    roles:
    - master
    - amd64
  image:
  - registry.cn-shenzhen.aliyuncs.com/cnmirror/kubernetes:v1.25.6-test
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
```

```
sealos apply -f Clusterfile
```
same errora and both have external and local parmeter
```
etcd:
  external:
    caFile: ""
    certFile: ""
    endpoints:
    - http://192.168.72.16:2379
    keyFile: ""
  local:
    dataDir: ""
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
```

**Comment by cuisongliu** [comment]
https://github.com/labring/sealos/pull/2704  retry it.

**Comment by willzhang** [comment]
> #2704 retry it.

fixed
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.35:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/calico:v3.24.5
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
      - https://192.168.72.40:2379
      - https://192.168.72.41:2379
      - https://192.168.72.42:2379
    caFile: /etc/etcd/pki/ca.crt
    certFile: /etc/etcd/pki/etcdctl-etcd-client.crt
keyFile: /etc/etcd/pki/etcdctl-etcd-client.key
```

**Comment by willzhang** [comment]
> #2704 retry it.

i have tested, and it fixed.
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.35:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/calico:v3.24.5
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
      - https://192.168.72.40:2379
      - https://192.168.72.41:2379
      - https://192.168.72.42:2379
    caFile: /etc/etcd/pki/ca.crt
    certFile: /etc/etcd/pki/etcdctl-etcd-client.crt
keyFile: /etc/etcd/pki/etcdctl-etcd-client.key
```
