### ISSUE TITLE
Feature: merge into Multiple yaml files

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2822]
### What is the problem this feature will solve?

A yaml file has multiple yaml configurations with `---`

https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```
---
kind: Namespace
apiVersion: v1
metadata:
  name: kube-flannel
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - clustercidrs
  verbs:
  - list
  - watch
```
this not work
```
sealos run registry.cn-shenzhen.aliyuncs.com/cnmirror/flannel:v0.21.3 --config-file flannel.yaml
```
The rendered yaml file will become chaotic

```
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: flannel
spec:
  path: manifests/config-map.yml
  match: registry.cn-shenzhen.aliyuncs.com/cnmirror/flannel:v0.21.3
  strategy: merge
  data: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-flannel-cfg
    data:
      net-conf.json: |
        {
          "Network": "100.64.0.0/16",
          "Backend": {
            "Type": "vxlan"
          }
        }
```
