### ISSUE TITLE
sealos run 可选参数问题

### ISSUE THREAD

**Issue by scau-han** [labring/sealos#2824]
### Detailed description of the question.

问题：sealos run labring/nginx:v1.23.2 安装helm chart应用时，是否支持外部文件方式，比如sealos run labring/nginx:v1.23.2 -f /path/prod-values.yml（-f 参数已经被使用）或者sealos run labring/nginx:v1.23.2 --values /path/prod-values.yml的方式？如果能支持，就不需要自己重新打包cloudimage，直接使用官方的即可。
已有支持：
目前sealos支持在Clusterfile.yaml文件配置Config，这种方式可以解决部分问题，但需要values.yml跟Config对比着修改，一旦改错还不好发现。
![1679022372815](https://user-images.githubusercontent.com/6700456/225802247-cb48e2c0-5f13-41c3-b678-63bc9b54c8c4.png)
个人想法：
1、sealos添加支持可选参数
2、Config支持外部文件覆盖
备注：不知道当前是否已经支持我提出的问题（我在文档中没有找到）

**Comment by willzhang** [comment]
https://github.com/labring-actions/cluster-image/tree/main/applications/ingress-nginx

**Comment by fengxsong** [comment]
因为run的时候镜像是个slice类型，如果支持直接传入类似helm的values参数的话，确实不好判断这个values文件是对哪个镜像的哪个文件进行patch。如果你对这方面有一些建议，也很欢迎你提下proposal哈:)

**Comment by bxy4543** [comment]
或者添加`sealos gen config -f raw-file-path -t to-image-path --type override` 这样对命令来根据raw文件来生成config文件

**Comment by willzhang** [comment]
> 因为run的时候镜像是个slice类型，如果支持直接传入类似helm的values参数的话，确实不好判断这个values文件是对哪个镜像的哪个文件进行patch。如果你对这方面有一些建议，也很欢迎你提下proposal哈:)

Is this ok?

```
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: nginx-config
spec:
  local_file: /root/nginx.values.yaml
  dest_file: charts/nginx/values.yaml
  match: labring/nginx:v1.23.3
  strategy: merge
```

merge仅适用于 YAML/JSON 文件
insert/append到文件中的数据
override覆盖文件中的内容

![image](https://user-images.githubusercontent.com/33590311/226087623-88377efc-eb0c-4f34-916f-9e1f3bf89d80.png)
