### ISSUE TITLE
BUG: cluster image kubernetes version cannot be empty

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2833]
### Sealos Version

v4.1.5
v4.1.7

### How to reproduce the bug?

```
root@ubuntu:~# cat Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.35:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/calico:v3.24.5
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
systemReserved:
  memory: "500m"
kubeReserved:
  memory: "500m"
cpuManagerPolicy: "static"
reservedSystemCPUs: "0,1"
topologyManagerPolicy: single-numa-node
```
apply
```
sealos apply -f Clusterfile
```
get clusterfile
```
root@ubuntu:~# cat /root/.sealos/default/Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-03-18T03:45:42Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.35:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/calico:v3.24.5
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status:
  commandCondition:
  - images: null
    lastHeartbeatTime: "2023-03-18T03:45:42Z"
    message: Applied to cluster successfully
    reason: Apply Command
    status: "True"
    type: ApplyCommandSuccess
  conditions:
  - lastHeartbeatTime: "2023-03-18T03:45:42Z"
    message: Applied to cluster successfully
    reason: Ready
    status: "True"
    type: ApplyClusterSuccess
  mounts:
  - env:
      criData: /var/lib/containerd
      defaultVIP: 10.103.97.2
      disableApparmor: "false"
      registryConfig: /etc/registry
      registryData: /var/lib/registry
      registryDomain: sealos.hub
      registryPassword: passw0rd
      registryPort: "5000"
      registryUsername: admin
      sandboxImage: pause:3.8
    imageName: hub.sealos.cn/labring/kubernetes:v1.25.6
    labels:
      auth: auth.sh
      check: check.sh $registryData
      clean: clean.sh && bash clean-cri.sh $criData
      clean-registry: clean-registry.sh $registryData $registryConfig
      image: ghcr.io/labring/lvscare:v4.1.6
      init: init-cri.sh && bash init.sh
      init-registry: init-registry.sh $registryData $registryConfig
      io.buildah.version: 1.28.1
      org.opencontainers.image.description: kubernetes-v1.25.6 container image
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.source: https://github.com/labring-actions/cache
      sealos.io.type: rootfs
      sealos.io.version: v1beta1
      version: v1.25.6
      vip: $defaultVIP
    mountPoint: /var/lib/containers/storage/overlay/4059a718fe198f789ce3fe14ad72f4c513b3e48f51ec0cd8e20c24aae755abc5/merged
    name: default-f7zyvex6
    type: rootfs
  - cmd:
    - cp -a opt/helm /usr/bin/
    imageName: hub.sealos.cn/labring/helm:v3.11.0
    labels:
      io.buildah.version: 1.28.1
    mountPoint: /var/lib/containers/storage/overlay/a93814ba6deaf3c3dcb7e3fcbebaed6fede19874ca0ca702b9b34a1a35fb6948/merged
    name: default-6cfolx1s
    type: application
  - cmd:
    - helm upgrade -i calico charts/calico -f charts/calico.values.yaml -n tigera-operator
      --create-namespace
    imageName: hub.sealos.cn/labring/calico:v3.24.5
    labels:
      io.buildah.version: 1.28.1
    mountPoint: /var/lib/containers/storage/overlay/7242af74121b5258936ee2fe615e73d84ea760b31a211b8062899ceaf0ddb42c/merged
    name: default-r729jy1i
    type: application
  phase: ClusterSuccess
```

apply Clusterfile again
```
root@ubuntu:~# sealos apply -f Clusterfile 
2023-03-18T12:00:38 info no nodes that need to be scaled
2023-03-18T12:00:38 info 
      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  Website: https://www.sealos.io/
                  Address: github.com/labring/sealos
                  Version: 4.1.7-ed0a75b9
```
run nginx app will give error
```
root@ubuntu:~# sealos run hub.sealos.cn/labring/nginx:v1.23.3
2023-03-18T11:47:57 info start to install app in this cluster
2023-03-18T11:47:57 info Executing SyncStatusAndCheck Pipeline in InstallProcessor
2023-03-18T11:47:57 info Executing ConfirmOverrideApps Pipeline in InstallProcessor
2023-03-18T11:47:57 info Executing PreProcess Pipeline in InstallProcessor
Error: failed to init runtime, cluster image kubernetes version cannot be empty
```
the final clusterfile
```
root@ubuntu:~# cat /root/.sealos/default/Clusterfile 
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-03-18T03:45:42Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.35:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/calico:v3.24.5
  - hub.sealos.cn/labring/nginx:v1.23.3
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status:
  commandCondition:
  - images: null
    lastHeartbeatTime: "2023-03-18T03:47:54Z"
    message: Applied to cluster successfully
    reason: Apply Command
    status: "True"
    type: ApplyCommandSuccess
  - images:
    - hub.sealos.cn/labring/nginx:v1.23.3
    lastHeartbeatTime: "2023-03-18T03:47:57Z"
    message: failed to init runtime, cluster image kubernetes version cannot be empty
    reason: Apply Command
    status: "False"
    type: ApplyCommandError
  conditions:
  - lastHeartbeatTime: "2023-03-18T03:47:54Z"
    message: Applied to cluster successfully
    reason: Ready
    status: "True"
    type: ApplyClusterSuccess
  phase: ClusterSuccess
```

### What is the expected behavior?

run nginx app success

### What do you see instead?

run nginx app again will failed

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```
