### ISSUE TITLE
BUG: brief description of the bug

### ISSUE THREAD

**Issue by zhengbucuo888** [labring/sealos#2872]
### Sealos Version

v4.1.7

### How to reproduce the bug?

我的部署配置为：敏感信息就不发出来了
```yaml
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
  - ips:
    - ...
    roles:
    - master
    - amd64
  - ips:
    - ...
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.25.0
  - labring/helm:v3.8.2
  - labring/calico:v3.24.1
  - labring/openebs:v3.4.0
  - labring/ingress-nginx:v1.5.1
  - labring/metrics-server:v0.6.2
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
status: {}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
    ## 增加api证书地址
    - ...
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
enforceNodeAllocatable:
- pods
evictionHard:
  imagefs.available: 15%
  memory.available: 2048Mi
  nodefs.available: 10%
  nodefs.inodesFree: 10%
```

![image](https://user-images.githubusercontent.com/31462232/228213340-c6ccbcff-9c83-4f23-9aa9-3e7f0e1b46d6.png)
默认安装会出现 apiserver.cluster.local不在证书列表里面。

### What is the expected behavior?

增加以下配置可以解决。
```yaml
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
...
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
    - "apiserver.cluster.local"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
...
```
---
但是还是出现问题，提示还是有ip不在证书内
![image](https://user-images.githubusercontent.com/31462232/228218902-a1ee8d6e-3285-4266-a85a-682bc6e6e556.png)
---
猜测应该是跟增加  certSANs有关系，最后去掉certSANs后部署成功。
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
  - ...
```
因为之前用4.1.3使用certSANs参数是没问题的。

### Operating environment

```markdown
- Sealos version:v4.1.7
- Kubernetes version: 1.25.0
```
