### ISSUE TITLE
Feature: Optimize Clusterfile structure

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2889]
### What is the problem this feature will solve?

This format is not friendly enough and there are duplicate configurations

![image](https://user-images.githubusercontent.com/33590311/229028456-b52f34ee-1e5d-462f-a236-6f92871edde6.png)

Adding a port configuration to an IP address is not a good format，and here have two ssh port config, Easily annoying

This format is more friendly
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  hosts:
    - {name: node1, address: 192.168.0.2, port: 22, user: root, password: "Sealos@123", pk: /root/.ssh/id_rsa, arch: amd64}
    - {name: node2, address: 192.168.0.3, port: 22, user: root, password: "Sealos@123", pk: /root/.ssh/id_rsa, arch: amd64}
    - {name: node3, address: 192.168.0.4, port: 22, user: root, password: "Sealos@123", pk: /root/.ssh/id_rsa, arch: amd64}
    - {name: node4, address: 192.168.0.5, port: 22, user: root, password: "Sealos@123", pk: /root/.ssh/id_rsa, arch: amd64}
    - {name: node5, address: 192.168.0.6, port: 22, user: root, password: "Sealos@123", pk: /root/.ssh/id_rsa, arch: amd64}
  roleGroups:
    master:
      - node1
      - node2
      - node3
    worker:
      - node4
      - node[5:10]
    registry:
      - node11    
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.24.1
```

Currently, sealos does not support automatic configuration of hostnames, which is the biggest problem that prevents automated installation， This configuration should solve the problem.

### If you have solution，please describe it

Adjusting the Clusterfile structure
