### ISSUE TITLE
 bug？sealos 4.2.0-alpha2

### ISSUE THREAD

**Issue by zhengbucuo888** [labring/sealos#2930]
### Detailed description of the question.

配置文件指定svc的子网，kubeadm config print init-defaults打印子网信息，好像还是默认的10.96.0.0/12，但是查看具体的svc地址是改了
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  serviceSubnet: 172.16.0.0/12
```
![image](https://user-images.githubusercontent.com/31462232/231120850-a8668bc6-3762-4fdc-b4b4-d8234e242b65.png)
```
SealosVersion:
  buildDate: "2023-03-30T07:58:04Z"
  compiler: gc
  gitCommit: 22baae1a
  gitVersion: 4.2.0-alpha2
  goVersion: go1.20.2
  platform: linux/amd64
```
