### ISSUE TITLE
Feature: templates support `range` `include` 

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#2994]
### What is the problem this feature will solve?

https://www.sealyun.com/docs/cli/apply#using-templates-experimental
here say:
but some template functions are missing, like include/tpl/require/lookup

is it possible support this missing feature.

```
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.30:22
    roles:
    - master
    - amd64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  ssh:
    passwd: "123456"
    pk: /root/.ssh/id_rsa
    port: 22
status: {}

---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: kube-ovn
spec:
  path: scripts/kube-ovn.env
  strategy: append
  match: registry.cn-shenzhen.aliyuncs.com/cnmirror/kube-ovn:v1.11.3
  data: |
  {{ range $key, $value := .Values.kubeovn }} 
    {{ $key | indent 2}}={{ $value }} 
  {{- end -}}
```
values.yaml
```
root@node30:~# cat values.yaml 
kubeovn:
  key1: value1
  key2: value2
```

and the result， bu range is not effiect
```
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: kube-ovn
spec:
  path: scripts/kube-ovn.env
  match: 123
  strategy: append
  data: |
    POD_CIDR=192.168.1.1
    POD_GATEWAY=192.168.1.2
```
