### ISSUE TITLE
BUG: Prompt message is repeated when prompt message is too long

### ISSUE THREAD

**Issue by nowinkeyy** [labring/sealos#3019]
### Sealos Version

main

### How to reproduce the bug?

1. sealos apply -f Clusterfile

Clusterfile (no hosts) :
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  name: default
spec:
  image:
  - hub.sealos.cn/labring/kubernetes:v1.25.6
  - hub.sealos.cn/labring/helm:v3.11.0
  - hub.sealos.cn/labring/flannel:v0.21.4
```

2. Prompt message appears and enter any character. 

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/72536832/235288199-4c3ff98b-3ff6-4e3a-abf2-ed265124a31c.png)

### What do you see instead?

You will see the prompt to print repeatedly. As follows :

![1682750738838](https://user-images.githubusercontent.com/72536832/235288127-45a4e365-40df-4246-a8b5-3e1b4996640c.png)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

This is the bug of promptui. For details, please see: [Label get repeated on a keyboard stroke](https://github.com/manifoldco/promptui/issues/122)
