### ISSUE TITLE
BUG: save clusterimage for apply

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3050]
### Sealos Version

main

### How to reproduce the bug?

1. After the clusterfile adds a new mirror, enter n in apply, and the mirror is not installed, and there will be no prompt for apply again, and the mirror is not installed.
2. After the clusterfile adds a new image, enter y in apply, and the image is installed successfully. After using rmi to delete the newly added image, there will be no prompt for apply again, and the image will not be installed.

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/4150905/236659501-48e99840-66d8-451b-a05c-331bb215a282.png">
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-05-07T05:14:34Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.64.101:22
    roles:
    - master
    - arm64
  image:
  - hub.sealos.cn/labring/kubernetes:v1.23.10
  - labring/helm:v3.8.2
  - labring/calico:v3.24.1
  - labring/coredns:v0.0.1
  - labring/kuboard:v3
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
```
