### ISSUE TITLE
BUG: apply single mode miss arch role

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3051]
### Sealos Version

main

### How to reproduce the bug?

1. write clusterfile 
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  image:
  - hub.sealos.cn/labring/kubernetes:v1.23.10
  - labring/helm:v3.8.2
  - labring/calico:v3.24.1
  - labring/coredns:v0.0.1
  - labring/kuboard:v3
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
status: {}
```
2. sealos apply -f clusterfile
3. cat ~/.sealos/default/Clusterfile

```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-05-07T05:35:13Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.64.97
    roles:
    - master
  image:
  - hub.sealos.cn/labring/kubernetes:v1.23.10
  - labring/helm:v3.8.2
  - labring/calico:v3.24.1
  - labring/coredns:v0.0.1
  - labring/kuboard:v3
  ssh:
    pk: /root/.ssh/id_rsa
    port: 22
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```
