### ISSUE TITLE
Feature: using release-drafter replace release note

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#3257]
### What is the problem this feature will solve?

https://github.com/sealerio/sealer/blob/main/.github/release-drafter.yml

**Comment by cuisongliu** [comment]
https://github.com/marketplace/actions/labeler 

```
name: "Pull Request Labeler"
 on:
 - pull_request_target

 jobs:
   triage:
     permissions:
       contents: read
       pull-requests: write
     runs-on: ubuntu-latest
     steps:
     - uses: actions/labeler@v4
       with:
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

```
command:
 - any: ['cmd/**/*', 'docs/commandline/**/*']

 area/doc:
 - any: ['docs/**/*']

 faq:
 - 'FAQ.md'

 test:
 - any: ['**/*_test.go']

 e2e-test:
 - any: ['test/**/*']

 plugin:
 - any: ['pkg/plugin/**/*']

 Clusterfile:
 - any: ['types/**/*']

 Adopter-Info:
 - 'Adopters.md'

 ImageBuilding:
 - any: ['build/**/*']
```
