### ISSUE TITLE
Feature: sealos clusterfile parse values with other string

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#3318]
### What is the problem this feature will solve?

config.yaml
```
etcd:
  endpoints:
    - 192.168.1.1
    - 192.168.1.2
    - 192.168.1.3
```
cluster.yaml, how can i add `https://` and `:2379` to ip address values in config.yaml，this not work
```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    caFile: /etc/etcd-certs/etcd-root-ca.pem
    certFile: /etc/etcd-certs/apiserver.pem
    keyFile: /etc/etcd-certs/apiserver-key.pem
    endpoints:
    {{- with .Values.etcd.endpoints }}
	- https://{{ . | toYaml | nindent 8 }}:2379
    {{- end }}
```
```
sealos apply -f Clusterfile.yaml --values config.yaml
```

it will be
```
- https://192.168.1.1 192.168.1.2 192.168.1.3:2379
```
not what i want
```
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
etcd:
  external:
    caFile: /etc/etcd-certs/etcd-root-ca.pem
    certFile: /etc/etcd-certs/apiserver.pem
    keyFile: /etc/etcd-certs/apiserver-key.pem
    endpoints:
    - https://192.168.1.1:2379
    - https://192.168.1.2:2379
    - https://192.168.1.3:2379
```
