### ISSUE TITLE
deploy cluster fail when I customize the calico config in Clusterfile

### ISSUE THREAD

**Issue by yangxggo** [labring/sealos#3380]
### Sealos Version

v4.2.1

### How to reproduce the bug?

1. 5 nodes(3 masters + 2 nodes) with clean OS
2. generate Clusterfile command:
`sealos gen labring/kubernetes:v1.23.17 labring/helm:v3.11.0 labring/calico:v3.24.1 --masters xxx,xxx,xxx --nodes yyy,yyy -p xxx > Clusterfile`
3. append calico configs to Clusterfile
```yaml
---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: calico
spec:
  path: charts/calico/values.yaml
  strategy: merge
  data: |
    installation:
      enabled: true
      kubernetesProvider: ""
      calicoNetwork:
        bgp: Disabled
        ipPools:
        - blockSize: 22
          cidr: 100.64.0.0/10
          encapsulation: VXLAN
        nodeAddressAutodetectionV4:
          interface: "bond.*|eth.*|en.*|em.*"
---
```
4. run it
`sealos apply -f Clusterfile`

### What do you see instead?

The instalation will be OK if I do not append the calico config to Clusterfile, but, when I do it, the calico will fail:

log: 
10.10.12.15:22  [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
10.10.12.15:22  [kubelet-start] Starting the kubelet
10.10.12.15:22  [kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
10.10.12.17:22  [preflight] Reading configuration from the cluster...
10.10.12.17:22  [preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
10.10.12.17:22  W0615 02:32:34.488435   10077 utils.go:69] The recommended value for "healthzBindAddress" in "KubeletConfiguration" is: 127.0.0.1; the provided value is: 0.0.0.0
10.10.12.17:22  W0615 02:32:34.499627   10077 utils.go:69] The recommended value for "resolvConf" in "KubeletConfiguration" is: /run/systemd/resolve/resolv.conf; the provided value is: /run/systemd/resolve/resolv.conf
10.10.12.17:22  [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
10.10.12.17:22  [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
10.10.12.17:22  [kubelet-start] Starting the kubelet
10.10.12.17:22  [kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
10.10.12.15:22
10.10.12.15:22  This node has joined the cluster:
10.10.12.15:22  * Certificate signing request was sent to apiserver and a response was received.
10.10.12.15:22  * The Kubelet was informed of the new secure connection details.
10.10.12.15:22
10.10.12.15:22  Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
10.10.12.15:22
2023-06-15T02:32:38 info succeeded in joining 10.10.12.15:22 as worker
10.10.12.17:22
10.10.12.17:22  This node has joined the cluster:
10.10.12.17:22  * Certificate signing request was sent to apiserver and a response was received.
10.10.12.17:22  * The Kubelet was informed of the new secure connection details.
10.10.12.17:22
10.10.12.17:22  Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
10.10.12.17:22
2023-06-15T02:32:40 info succeeded in joining 10.10.12.17:22 as worker
2023-06-15T02:32:42 info start to sync lvscare static pod to node: 10.10.12.17:22 master: [10.10.12.7:6443 10.10.12.19:6443 10.10.12.32:6443]
2023-06-15T02:32:42 info start to sync lvscare static pod to node: 10.10.12.15:22 master: [10.10.12.7:6443 10.10.12.19:6443 10.10.12.32:6443]
10.10.12.15:22  2023-06-15T02:32:42 info generator lvscare static pod is success
10.10.12.17:22  2023-06-15T02:32:42 info generator lvscare static pod is success
2023-06-15T02:32:42 info Executing pipeline RunGuest in CreateProcessor.
Release "calico" does not exist. Installing it now.
Error: template: tigera-operator/templates/tigera-operator/02-tigera-operator.yaml:62:30: executing "tigera-operator/templates/tigera-operator/02-tigera-operator.yaml" at <.Values.tigeraOperator.version>: nil pointer evaluating interface {}.version
2023-06-15T02:32:46 error Applied to cluster error: exit status 1
Error: exit status 1

PS: 
All things are OK when I use sealos v4.2.0( even if I append the same calico config to the Clusterfile).

### Operating environment

```markdown
- Sealos version: v4.2.1
- kubernetes version: labring/kubernetes:v1.23.17 OR labring/kubernetes-docker:v1.23.16, both fail
- Operating system: ubuntu20.04
- Runtime environment: virtual machine (openstack 8c8g40g)
- Cluster size: 3masters, 2nodes
```
