### ISSUE TITLE
BUG: Failed to add nodes to the cluster using diff ssh options

### ISSUE THREAD

**Issue by SpringHgui** [labring/sealos#3492]
### Sealos Version

 4.2.0

### How to reproduce the bug?

参考 #1941 的问题，尝试增加节点

因为每个节点的ssh密码不同，所有修改下面ssh密码，然后添加节点
```
[root@svrhz8-3 ~]# cat /root/.sealos/default/Clusterfile
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-05-24T03:54:52Z"
  name: default
spec:
  hosts:
  - ips:
    - 172.16.21.247:22
    roles:
    - master
    - amd64
  - ips:
    - 172.16.21.249:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes-docker:v1.27.2
  - labring/helm:v3.11.3
  - labring/calico:v3.25.1
  ssh:
    passwd: *****
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status:
  commandCondition:
  - images:
    - labring/kubernetes-docker:v1.27.2
    - labring/helm:v3.11.3
    - labring/calico:v3.25.1
    lastHeartbeatTime: "2023-05-24T03:54:52Z"
    message: Applied to cluster successfully
    reason: Apply Command
    status: "True"
    type: ApplyCommandSuccess
  - images: null
    lastHeartbeatTime: null
    status: ""
    type: ""
  conditions:
  - lastHeartbeatTime: "2023-05-24T03:54:52Z"
    message: Applied to cluster successfully
    reason: Ready
    status: "True"
    type: ApplyClusterSuccess
```

本次新增节点`172.16.21.245`，但是报错是之前添加的一个子节点`172.16.21.249`的密码问题，密码已经被修改为`172.16.21.245`的密码了，当然验证不通过

```
[root@svrhz8-3 ~]# sealos add --nodes 172.16.21.245
2023-07-12T11:22:52 info start to scale this cluster
2023-07-12T11:22:52 info Executing pipeline JoinCheck in ScaleProcessor.
Error: failed to run checker: checker: failed to create ssh client, failed to connect 172.16.21.249:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

### Operating environment

```markdown
- Sealos version:  4.2.0
```

### Additional information

#1941 只能解决当只有主节点时添加一个子结点，如果继续新增子节点，还是要所有子节点的密码相同？
