### ISSUE TITLE
BUG: sealos apply not check Duplicate of hostname

### ISSUE THREAD

**Issue by willzhang** [labring/sealos#3527]
### Sealos Version

v4.3.0

### How to reproduce the bug?

Clusterfile.yaml
```
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: "2023-07-18T06:50:48Z"
  name: default
spec:
  hosts:
  - ips:
    - 192.168.72.30
    - 192.168.72.31
    - 192.168.72.32
    roles:
    - master
    - amd64
  image:
  - docker.io/labring/kubernetes:v1.27.3-4.3.0
  ssh:
    passwd: "123456"
    pk: ~/.ssh/id_rsa
    port: 22
    user: root
```

```
sealos apply -f Clusterfile.yaml
```

### What is the expected behavior?

install ha cluster success.

### What do you see instead?

join the second master node etcd will failed, because all 3 nodes have same hostname with ubuntu.

when change hostname to node1 node2 node3, install success.

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

Sealos needs to force a check for duplicate host names
