### ISSUE TITLE
BUG: FATA[0003] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "sealos.hub:5000/pause:3.8": failed to resolve reference "sealos.hub:5000/pause:3.8": sealos.hub:5000/pause:3.8: not found

### ISSUE THREAD

**Issue by bxy4543** [labring/sealos#4117]
### Sealos Version

4.3.5

### How to reproduce the bug?

full content：https://paste.ubuntu.com/p/szYhfm2S42/

fail content：
73 line:
```
2023-10-19T08:41:58 warn cannot connect to remote temporary registry: Get "http://103.140.232.12:5050": dial tcp 103.140.232.12:5050: connect: connection refused, fallback using ssh mode instead
```
151 line:
```
E1019 08:42:32.241019  112327 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"sealos.hub:5000/pause:3.8\": failed to resolve reference \"sealos.hub:5000/pause:3.8\": sealos.hub:5000/pause:3.8: not found" image="sealos.hub:5000/pause:3.8"
FATA[0003] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "sealos.hub:5000/pause:3.8": failed to resolve reference "sealos.hub:5000/pause:3.8": sealos.hub:5000/pause:3.8: not found
```

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

```
root@sos:~# uname -a
Linux sos.ai101.eu.org 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:29:36 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
root@sos:~# sealos version
SealosVersion:
  buildDate: "2023-10-09T10:07:15Z"
  compiler: gc
  gitCommit: 881c10cb
  gitVersion: 4.3.5
  goVersion: go1.20.8
  platform: linux/arm64
```
